/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REGISTRATION_H_RPCGEN
#define _REGISTRATION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct record {
	char serial_Number[50];
	char Reg_Number[50];
	char Name[100];
};
typedef struct record record;

#define REGISTRATION_PROG 0x23451111
#define REGISTRATION_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define registration 1
extern  char ** registration_1(record *, CLIENT *);
extern  char ** registration_1_svc(record *, struct svc_req *);
extern int registration_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registration 1
extern  char ** registration_1();
extern  char ** registration_1_svc();
extern int registration_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_record (XDR *, record*);

#else /* K&R C */
extern bool_t xdr_record ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REGISTRATION_H_RPCGEN */
