/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HEZRON_H_RPCGEN
#define _HEZRON_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct proc_2_1_argument {
	int arg1;
	char *x;
};
typedef struct proc_2_1_argument proc_2_1_argument;

#define HEZRON 0x20000001
#define HEZRON_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROC_2 2
extern  char ** proc_2_1(int , char *, CLIENT *);
extern  char ** proc_2_1_svc(int , char *, struct svc_req *);
extern int hezron_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROC_2 2
extern  char ** proc_2_1();
extern  char ** proc_2_1_svc();
extern int hezron_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_proc_2_1_argument (XDR *, proc_2_1_argument*);

#else /* K&R C */
extern bool_t xdr_proc_2_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HEZRON_H_RPCGEN */
