/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	int operation;
	float op1;
	float op2;
};
typedef struct operands operands;

#define CALCULATE_PROG 0x23451111
#define CALCULATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define calculate 1
extern  float * calculate_1(operands *, CLIENT *);
extern  float * calculate_1_svc(operands *, struct svc_req *);
extern int calculate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calculate 1
extern  float * calculate_1();
extern  float * calculate_1_svc();
extern int calculate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
