/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

float *
calculate_1_svc(operands *argp, struct svc_req *rqstp)
{
	
	static int operation_selector;
	static float result,temp_result, operand1, operand2;

	/*
	 * insert server code here
	 */
;
	printf("\nRequest received from client\n");
	operation_selector=argp->operation;
	operand1=argp->op1;
	operand2=argp->op2;

	switch(operation_selector){
	     case 1: //Addition
		temp_result = operand1 + operand2;
		printf("\t%f + %f = %f\n", operand1, operand2, temp_result);
		break;	
	     case 2: //Subtraction
		temp_result = operand1 - operand2;
		printf("\t%f - %f = %f\n", operand1, operand2, temp_result);
		break;	
	     case 3: //Multiplication
		temp_result = operand1 * operand2;
		printf("\t%f * %f = %f\n", operand1, operand2, temp_result);
		break;	
	     case 4: //Division
		temp_result = operand1 / operand2;
		printf("\t%f / %f = %f\n", operand1, operand2, temp_result);
		break;	
	     default: //default action
		break;	

	}
	
	printf("Return result to client\n");
	result = temp_result;

	return &result;
}
