/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"

bool_t
xdr_operands (XDR *xdrs, operands *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->operation))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->op1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->op2))
		 return FALSE;
	return TRUE;
}
